force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <description>sObject para view, create e edit de fornecedores.</description>
    <label>Fornecedor</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Nome de Fornecedor</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <description>Nome do fornecedor</description>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <label>Produto</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Escolha uma ou mais opções</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Telefone__c.field-meta.xml
<CustomField>
    <fullName>Telefone__c</fullName>
    <description>Telefone do fornecedor</description>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/FornecedoresController.cls
public with sharing class FornecedoresController {
	// STERN LECTURE ABOUT WHAT'S MISSING HERE COMING SOON
	@AuraEnabled
    public static List<Fornecedor__c> getFornecedores() {
        // Check to make sure all fields are accessible to this user
        String[] fieldsToCheck = new String[] {
            'Id', 'Name', 'Nome__c', 'Produto__c', 'Telefone__c', 'Email__c', 'CNPJ__c'
        };
        Map<String,Schema.SObjectField> fieldDescribeTokens =
            Schema.SObjectType.Fornecedor__c.fields.getMap();
        for(String field : fieldsToCheck) {
            if (! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
            }
        }
        return [SELECT Id, Name, Nome__c, Produto__c, Telefone__c, Email__c, CNPJ__c
               FROM Fornecedor__c];
    }

    // FIXAR O REGISTRO NO SOBJECT DA SALESFORCE
    @AuraEnabled
    public static Fornecedor__c saveFornecedor(Fornecedor__c fornecedor){
        // Perform isUpdateable() checking first, then
        upsert fornecedor;
        return fornecedor;
    }
}